

-- Exemplo de relação muitos para muitos
CREATE TABLE alunos (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(100) PRIMARY KEYOT NULL,
    idade VARCHAR(100) PRIMARY KEYOT NULL,
    email VARCHAR(100) PRIMARY KEYOT NULL,
    senha VARCHAR(100) PRIMARY KEYOT NULL,
)

CREATE TABLE cursos (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(50) NOT NULL,
)

